name: fxdialogs
description: A Flutter package to use custom dialogs.
version: 0.0.3+5
homepage: https://github.com/Ian-Munashe/fx_dialogs

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

