name: fxdialogs
description: A Flutter package to use custom dialogs.
version: 0.1.0
homepage: https://github.com/Ian-Munashe/fx_dialogs

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.4
  lottie: ^1.2.2
  collection: ^1.15.0
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

