name: fxdialogs
description: A new Flutter package project.
version: 0.0.3+1
homepage: https://github.com/Ian-Munashe/fx_dialogs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
